---
- hosts: arista
  vars:
   ansible_python_interpreter: /usr/bin/python3

#this playbook was tested to ssh into arista devices, gather information and then populate it to a netbox
#you must use your own netbox url and netbox token
#be sure to set your own site, and tenant
  - name: "TASK 100: NETBOX >> ADD DEVICE TO NETBOX"
    netbox.netbox.netbox_device:
      netbox_url: 'https://X.X.X.X'
      netbox_token: 'tokengoeshere'
      validate_certs: false
      data:
        name: "{{ ansible_hostname }}"
        device_type: "{{ ansible_cmdline['platform'] }}"
        platform: "{{ ansible_cmdline['platform'] }}"
        serial: "{{ ansible_facts['ansible_board_serial'] }}"
        serial: "{{ ansible_board_serial }}"
        status: Active
        #device_role: "{{ inventory_hostname | get_role_from_hostname }}"
        #device_role: "{{ ansible_hostname }}"
        device_role:  networkgear
        site: Placeholder
        tenant: Placeholder
      delegate_to: localhost

  - name: "TASK 110: NETBOX >> ADD INTERFACES TO NETBOX"
    vars:
    netbox.netbox.netbox_device_interface:
      netbox_url: 'https://X.X.X.X'
      netbox_token: 'tokengoeshere'
      validate_certs: false
      data:
        device: "{{ ansible_hostname }}"
        type: other
        #description: "{{ item['description'] }}"
        #mac_address: "{{ ansible_facts[item]['macaddress'] }}"
        name: "{{ ansible_facts[item]['device'] }}"
      state: present
    with_items: "{{ ansible_interfaces }}"
    delegate_to: localhost
